# Generated by Django 3.2.5 on 2023-01-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_userprofile_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='adress',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images', verbose_name='Imagen de perfil'),
        ),
    ]
